name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build with Make
      run: cmake --build build

    - name: Build with Makefile
      run: make -C build
